### ISSUE TITLE
Feature Request: Spelunky Classic and Another Metroid 2 Remake

### ISSUE THREAD

**Issue by danielthewise** [krishenriksen/AnberPorts#1]
Hello, are you taking requests for new ports? If so, I'd love it if you'd take a look at porting [Spelunky Classic](https://www.moddb.com/games/spelunky-classic/downloads/spelunky-source-code) and [Another Metroid 2 Remake](https://github.com/Lojemiru/AM2R-Community-Updates)
(Links to open source code for each game). 

I'm not tech savvy enough to know whether it's possible to port either of these games to the 351, but I do know that Android ports of them are playable on the Retroid Pocket 2.

Thanks for checking it out!

**Comment by Albinoinverso** [comment]
Make this possible pleaaaaase

**Comment by krishenriksen** [comment]
Only if there is source code somewhere.

**Comment by krishenriksen** [comment]
For now not possible, but you can play it here, https://www.lexaloffle.com/bbs/?pid=56554

**Comment by krishenriksen** [comment]
Hi, I found a way, and Spelunky Classic is now available.
