### ISSUE TITLE
Half Life Camera Drift

### ISSUE THREAD

**Issue by leighg101** [krishenriksen/AnberPorts#10]
Hey,
I installed half life on my RG351P tonight and I noticed that the camera keeps moving upwards slowly on the right analog stick, only does it on half-life

**Comment by krishenriksen** [comment]
Will have to investigate this.

**Comment by uv54633** [comment]
The camera drift in Half-Life was caused by deadzone issues in the version of Ark OS it occurs in. You just need to update your Ark OS to the latest release and it should stop.

**Comment by leighg101** [comment]
Hey, 
I just checked and I’m on the latest ArkOS as it tells me there is no other updates. I’ve also noticed that when pressing start instead of pausing it just quits the games. Done a video below showing the problems in real time

https://youtu.be/UYlMhzx5hmA

**Comment by uv54633** [comment]
That's odd, I use the Half-Life included with Ark OS and did experience that problem at one point.
It may just be that the Half-Life from Anberports may just need to be updated.

**Comment by uv54633** [comment]
If you want to fix the start button quitting the game here is a remap file to try:
https://retrogamecorps.files.wordpress.com/2020/12/controller-update.zip
Just put the file contents in your valve folder.

**Comment by leighg101** [comment]
That fixed the pause thanks.

I just check an even re-installing half-life from the application an then loading it still does it. Also noticed that if you pause, leave it then unpause the camera will have moved. Video below 

https://youtu.be/FbBmIgB5DAE

**Comment by uv54633** [comment]
Here is the version of Half-Life I have that doesn't have the drift. Just copy the files into the Half-Life folder in your ports section and then copy the files from the zip folder "Copy Contents into Valve folder" into the Valve folder. This may provide a fix.
[HalfLife.zip](https://github.com/krishenriksen/AnberPorts/files/5966591/HalfLife.zip)

**Comment by leighg101** [comment]
Sadly this hasn’t fix it, I’ve no idea why it’s doing it

**Comment by uv54633** [comment]
I am not sure then what is the cause. I hope eventually it does get fixed in the future.

**Comment by leighg101** [comment]
I’ve just run into another problem. I’ve just installed Quake 2, copies the pak files to the baseq2 folder, press on Quake 2 it goes black then returns to the ports menu

**Comment by uv54633** [comment]
Where did you get the pak files?

**Comment by leighg101** [comment]
From my steam copy of Quake 2. The pak files are all lower case as well

**Comment by uv54633** [comment]
Try these Quake 2 Files that came from the original disc for the game:
https://drive.google.com/file/d/1zHrhhHMNIvlQFWkKyX-rUHwrnMNTX_u7/view?usp=sharing

**Comment by uv54633** [comment]
I just tried the version of Half-Life from Anberports and encountered no drift.
I would recommend making sure Ark OS and Anberports are up to date, deleting both the Half-Life folder and Half-Life.sh file from the ports, and then redownloading the game from Anberports as I got the most recent version and it has no problem. Make sure you recopy the controller config files I sent earlier back into the valve folder.

https://youtu.be/0yOjatcfIoA

**Comment by leighg101** [comment]
No go on either I’m afraid. No idea what’s going on with Quake 2 and Half-Life is odd, but someone else on Reddit has the same problem with Half-Life

**Comment by uv54633** [comment]
That is super odd how that is happening. Sorry I couldn’t help find a solution. Hopefully they end up working eventually.

**Comment by leighg101** [comment]
That’s ok, thanks for trying to help out

**Comment by krishenriksen** [comment]
Some rg351 devices has issues with the usb controller. For example my controls doesn't work when I boot the device, unless I sleep it a few times.

Might be the same for you, and unsure if it's fixable.

**Comment by uv54633** [comment]
I think I found a solution for the drift. Unzip this and put the config.cfg file into your valve folder and have it overwrite. The file has an adjusted deadzone settings in which to possibly stop the camera drift.

[config.zip](https://github.com/krishenriksen/AnberPorts/files/5983421/config.zip)

**Comment by leighg101** [comment]
That fixed it! Thanks so much for doing that!

**Comment by krishenriksen** [comment]
Updated package with config file, thank.
