### ISSUE TITLE
Suggestion: OpenXcom port

### ISSUE THREAD

**Issue by Wolod** [krishenriksen/AnberPorts#11]
Hello!

I learned about AnberPorts today and it's an awesome project! I noticed that Star Control 2: The Ur-Quan Masters is ported already. So I wanted to know if there are any plans to port another open-source project called OpenXCom or OpenXCom Extended (which is even better because it supports more mods)? I asked this question on the Discord and was told to add a suggestion here. So consider this message as my vote on AnberPorts Wiki :)

Source for the game can be found here:
https://openxcom.org/git-builds/

**Comment by krishenriksen** [comment]
Cannot open the link.

**Comment by Wolod** [comment]
That's weird openxcom.org works just fine for me. Here is their github https://github.com/OpenXcom

**Comment by daedalia** [comment]
I was thinking this could be some work to convert for use without a touchscreen but seems some guy has already done this, porting it to the RG350. I can dig this out of there's interest.

**Comment by Wolod** [comment]
Sounds very promising. Hope to see rg351 port soon.
