### ISSUE TITLE
Stadia - Reopen game to play

### ISSUE THREAD

**Issue by ryandavidmercado** [krishenriksen/AnberPorts#12]
After successfully logging in to Stadia by swapping back and forth between my Wifi dongle and a USB keyboard, I'm able to see the Stadia interface upon opening the app.

However, attempting to play any game leads to a particularly long load time, followed by a dialog stating "Reopen game - Reopen the game to play." Attempting to reopen the game leads to the same long load time, followed by the same message.

**Comment by krishenriksen** [comment]
Not quite ready yet, but getting there slowly.
