### ISSUE TITLE
Nvidia Geforce Now

### ISSUE THREAD

**Issue by B3N313** [krishenriksen/AnberPorts#14]
Hi, first of all, thank you very much for all the work you put into this.

How does Nvidia Geforce Now even work? when I open it there is a webbrowser with the geforce now site opened.
I can't logg in, as I can't type, there is no way to show a keyboard on screen.

What am I meant to do?

**Comment by krishenriksen** [comment]
Work in process. A virtual keyboard will be added at some point.
