### ISSUE TITLE
Suggestion: Oolite

### ISSUE THREAD

**Issue by Starlapses** [krishenriksen/AnberPorts#15]
Oolite is an open source Elite clone with a Linux version, so possibly a good candidate?
https://github.com/OoliteProject/oolite

Also possibly a very bad candidate due to the number of controls...

Having an Elite style game would be amazing, although maybe I should just be content with UQM :)

Thanks for Descent and Quake, you made me very happy.

**Comment by Txori** [comment]
Oolite would be greatly appreciated indeed.

I ported Glfrontier (frontier Elite II) to the PSP years ago, which had less buttons than the RG351, and I was very happy how I managed to fit everything on that system.

You'll find information about my buttons layout here if needed: https://www.txori.com/index.php?static2/frontier

**Comment by Starlapses** [comment]
That's amazing, I'll have to try it on my psp. Thanks for letting me know. I wonder if it would play well with the psp emulator? I'll try it and see what happens, will let you know.

**Comment by Txori** [comment]
It should play well. It was working perfectly on PPSSPP for OUYA 7 years ago: https://www.txori.com/index.php?article73/frontier-sur-psp-sur-emulateur-sur-ouya
(It's in french)

**Comment by Starlapses** [comment]
It does! That's wonderful, I'm going to dive in and get lost in that world for a few days. Thank you so much.

I'm not saying Oolite wouldn't still be nice, though :)

**Comment by Starlapses** [comment]
I'm having so much fun with your port of frontier, Txori, that I think I would continue playing it over Oolite anyway! I'm wondering if we should close this suggestion down, but Oolite does fill a slightly different niche (a bit more accessible, better graphics etc). 

Definitely with Kreal having a lot on his plate your Frontier port really scratches the itch for anybody looking for space adventuring goodness. I imagine you have played it to death though :D
