### ISSUE TITLE
Wolfenstein won't work

### ISSUE THREAD

**Issue by TheShiv14** [krishenriksen/AnberPorts#15]
When you download the Wolfenstein port to ArkOS, and all the game files are added and stuff, the port just crashes everytime it starts up.

**Comment by krishenriksen** [comment]
Did you add the games files to the ecwolf folder?

**Comment by TheShiv14** [comment]
Even when adding Wolf3d.EXE file, it just crashes when trying to open the game

**Comment by krishenriksen** [comment]
Possible for you to log in via SSH, and start it this way, providing me with whatever output you get ?

**Comment by TheShiv14** [comment]
okay. I updated Anberports, uninstalled and reinstalled the Wolfenstein port, and it still crashes, but it does not give a log.txt document at all

**Comment by krishenriksen** [comment]
There should be a log.txt located in /roms/ports/ecwolf/
