### ISSUE TITLE
Feature Request: The Clou / the sting port

### ISSUE THREAD

**Issue by thehype1234** [krishenriksen/AnberPorts#18]
Is it possible to use the sdl port of the Clou to port it over to arkos? 

https://github.com/vcosta/derclou

Great work so far! 😉👍

**Comment by krishenriksen** [comment]
Done, enjoy.

**Comment by thehype1234** [comment]
Thank you! 👍 unfortunately I can't find it in anberports on the rg351p...

Updated and not there!?

**Comment by krishenriksen** [comment]
It's called "The-Clue" there. Apparently that's the English name yes?

**Comment by thehype1234** [comment]
Yes, that's right... but even this is not showing up! I will try reinstall anberports. I have the feeling that update isn't doing anything!

**Comment by thehype1234** [comment]
No luck... it doesn't show up. Even in the scripts folder... nothing there.

**Comment by thehype1234** [comment]
Added it manually for now... maybe the update doesn't include the files? Even in the games list in anberports file it hasn't shown up after update!? 

Thank you so much for porting it over!

**Comment by krishenriksen** [comment]
My new version management didn't allow for old version to update. I added a fix, you should be able to update now.

**Comment by thehype1234** [comment]
Two things I was noticing...

1. the Game hangs sometimes or the controls with the d-pad have a problem. To select something within the game I have to press: down down up to go one line down and wise versa

2. one key is missing to save or load the game... f1-f10 is used for a menu to save and load. See the picture of the original manual.

![image](https://user-images.githubusercontent.com/11811235/108281547-38f0f480-7180-11eb-8322-e3218e6e495e.png)

**Comment by krishenriksen** [comment]
Updated.
F1 = x
F2 = y
F3 = L1
F4 = R1
F5 = L2
F6 = R2
Left mouse = R3
Right mouse = L3

Also improved d-pad.

**Comment by thehype1234** [comment]
You are awesome... I will try it and respond! Thank you!
