### ISSUE TITLE
Moonlight not showing a code

### ISSUE THREAD

**Issue by ramia15** [krishenriksen/AnberPorts#2]
When trying to run moonlight embedded, I enter my Desktop's  name and I get a notification on my desktop that the device is trying to pair but on the device itself it just has the blinking '-' and does not present me a code to enter, so I am unable to pair with the computer.

Device: RG351P 
OS: ArkOS

EDIT: Tried entering the computer's IP address and still had the same issue

**Comment by krishenriksen** [comment]
Try the new version.
