### ISSUE TITLE
wont work on 351elec firmware

### ISSUE THREAD

**Issue by jdanielromer** [krishenriksen/AnberPorts#21]
tried it on my RG351P with the 351elec firmware but every time I boot it up it will freeze and I will have to reset my device to use it again.

**Comment by krishenriksen** [comment]
351elec compatibility coming soon.

**Comment by jdanielromer** [comment]
> 351elec compatibility coming soon.

any estimated time frame?

**Comment by krishenriksen** [comment]
Once I receive my testing devices from china, but being new year for them, it might take a month.

**Comment by szalik-rg351** [comment]
you can also buy spare card - something like 32/64gb card for tests
