### ISSUE TITLE
Feature Request: GTA 3

### ISSUE THREAD

**Issue by Disfunktional** [krishenriksen/AnberPorts#22]
https://github.com/GTAmodding/re3

Don't know if it'll run on rg351p or not, works on Linux so guess it should work, obvs performance might be another matter :)

**Comment by krishenriksen** [comment]
In progress.

**Comment by krishenriksen** [comment]
The code was taken down, so unsure about the future of this one.

**Comment by Disfunktional** [comment]
Fair enough and fingers crossed it finds its way back...
Thanks for all your efforts!
