### ISSUE TITLE
REQUEST: OneShot port

### ISSUE THREAD

**Issue by thisjustin2001** [krishenriksen/AnberPorts#24]
Hello! As the title says, I'm hoping that the fork of EasyRPG made specifically to run OneShot legacy could be ported to Anberports! This is my single most wanted RG351 port, so I hope you'll take a look at it for me.

Here's the GitHub link: https://github.com/20kdc/EasyRPG-Player-Fork-For-OneShot-Legacy

Thanks for your consideration!

**Comment by levidunc** [comment]
yes

**Comment by levidunc** [comment]
i would love that
