### ISSUE TITLE
Issues on running against 351elec firmware (missing libX11.so.6)

### ISSUE THREAD

**Issue by jayjun911** [krishenriksen/AnberPorts#24]
I've noticed following issues
- 351elec doesn't have 'sudo' thus generates warning
- oga_control not loading, ssh'd ./oga_control & fixed
- following errors are observed... (How do I get libX11.so.6??)

./moonlight-embedded: line 198: rg351p-js2xbox: command not found chmod: /dev/input/by-path/platform-odroidgo2-joypad-event-joystick: No such file or directory kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec] ./moonlight: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory

**Comment by krishenriksen** [comment]
yep, not yet compatible with 351elec, but will be soon.
