### ISSUE TITLE
2/20 update , everything stopped working

### ISSUE THREAD

**Issue by Vendo232** [krishenriksen/AnberPorts#29]
Installed 1.0.5 today, install CS, Spelinky and already running games stopped working eDuke, Half Life, please help

**Comment by krishenriksen** [comment]
If something bad like that happens, run this via SSH

sudo ln -sf /usr/local/lib/aarch64-linux-gnu/libgbm.so.1.0.0 /usr/local/lib/aarch64-linux-gnu/libgbm.so.1
sudo ln -sf /usr/local/lib/aarch64-linux-gnu/libEGL.so.1.0.0 /usr/local/lib/aarch64-linux-gnu/libEGL.so.1

**Comment by Vendo232** [comment]
reinstalled all
