### ISSUE TITLE
Perfect Dark

### ISSUE THREAD

**Issue by Alpha-Betty** [krishenriksen/AnberPorts#31]
Not even sure if it's possible but there is the decompilation src files on github.

https://github.com/n64decomp/perfect_dark

**Comment by krishenriksen** [comment]
Not good enough on Nintendo 64 emulator ?

**Comment by Alpha-Betty** [comment]
thanks for looking.  ill try and tweak some settings and get back to you

**Comment by Alpha-Betty** [comment]
Yer it's PD is working ok in arkos,  but 007 with the same settings is still unplayable.
