### ISSUE TITLE
Blood - Camera drift and movement 

### ISSUE THREAD

**Issue by eckert2021** [krishenriksen/AnberPorts#33]
[nblood.log](https://github.com/krishenriksen/AnberPorts/files/6016925/nblood.log)
[log.txt](https://github.com/krishenriksen/AnberPorts/files/6016926/log.txt)

Basically when I start the game the camera just starts spinning around as well as the character starts walking without any directional input whatsoever. Besides, it seems that the left analog stick is useless (the right analog works though).

I have attached the log script above.

**Comment by krishenriksen** [comment]
Thank you for the log files, it seems the joystick deadzone is difference from device to device. Don't know if I can fix this.

**Comment by eckert2021** [comment]
Oh, that’s a pitty :/
I was really looking forward to playing this game on the go. Hopefully at least Half Life has been playing smoothfully. 

Well, I still hope someone can crack this nut. As per the log files, you’re welcome! I am the one who has to thank you for all your effort.

**Comment by eckert2021** [comment]
Just an update. I had been having the same issues with the shareware version of Doom available on Retroarch. Ever since I changed the deadzone to "20%" (the default was 15%), my problem was solved. Is there anyway I  change the analog deadzone information to that value too?

**Comment by eckert2021** [comment]
Isn't there, by chance, anyway to disable the left analog stick for this game (or even both of them)? Since the digital pad does the same inputs it should fix the problem if the issue is with the left analog alone.

**Comment by krishenriksen** [comment]
fixed.
