### ISSUE TITLE
Spelunky and AM2R Problem

### ISSUE THREAD

**Issue by Albinoinverso** [krishenriksen/AnberPorts#34]
![IMG_20210221_201949](https://user-images.githubusercontent.com/76804309/108652236-64d2e980-74a2-11eb-97ec-7cdc3abcd8df.jpg)
Hello and good morning/afternoon/Night Mr Kris. I have this kind of Flower background screen when launch any of this games and no go any far from that screen. I can move the pointer with the lef stick but no more than that. I use the most recent Arkos version (02202021) and the last Amberports version too.

**Comment by asc82** [comment]
The same is happening to me with both games.

**Comment by krishenriksen** [comment]
Try updating to AnberPorts 1.0.9, just pushed today.

**Comment by Albinoinverso** [comment]
![16140358840667481475723905052559](https://user-images.githubusercontent.com/76804309/108782850-1cbbd180-754b-11eb-9a3e-911b814f3b16.jpg)
Update Anberports and even download again AM2R and Spelunky and both games keep in this mouse/Flower screen. Maybe i just press some button? Dont presss any? Thanks in advance Kris

**Comment by nullstalgia** [comment]
Same here on the one just pushed.

**Comment by krishenriksen** [comment]
checking

**Comment by krishenriksen** [comment]
Ok, try update both AnberPorts and reinstall game.

**Comment by nullstalgia** [comment]
Still no dice, now it's on the ArkOS Please Wait... screen with the cursor.

**Comment by krishenriksen** [comment]
And what does log.txt file says located in /roms/ports/spelunky or /roms/ports/AM2R ?

**Comment by nullstalgia** [comment]
AM2R Log: https://gist.github.com/nullstalgia/62b78f53f794514b8c2130a2633e264c

Spelunky Log: https://gist.github.com/nullstalgia/5f7c55bc01acee143ded4195efa04e8b

**Comment by Albinoinverso** [comment]
According what i see in the first one says something a "ini" files, missing something about assets. On the second one dont recognize the 351 controls

**Comment by krishenriksen** [comment]
And you are using ArkOS correct ?

**Comment by Albinoinverso** [comment]
Yes, Arkos both me and @nullstalgia

**Comment by asc82** [comment]
After the update to 1.1.0 I first got a solid blue screen, no more flowers, and now only a black screen with a blinking cursor.

**Comment by OatmealParmesan** [comment]
I'm getting the blue screen as well with ArkOS and AnberPorts up to date.

**Comment by krishenriksen** [comment]
Give it a try now, reinstall AM2R or Spelunky.

**Comment by OatmealParmesan** [comment]
Now I'm seeing "Reboot device, please stand by ... "

**Comment by krishenriksen** [comment]
should be fix in the new new update.

**Comment by Albinoinverso** [comment]
![16142057414798435301006159226258](https://user-images.githubusercontent.com/76804309/109074479-92a07400-76d6-11eb-92b5-e363380455c4.jpg)
Same here, i update today and got the solid blue screen too. Cheers Kreal, we will be patient here

**Comment by krishenriksen** [comment]
You have to be patient. There is nothing else you can do.

**Comment by nullstalgia** [comment]
Just to make sure, Commit [34fea51](https://github.com/krishenriksen/AnberPorts/commit/34fea51690eccae6ac02a945c4d1e1d4d8d81dbf) states that you updated Spelunky and AM2R, but the scripts stayed the same. Is it possible you forgot to commit those? Or am I missing some other things that were changed

**Comment by krishenriksen** [comment]
No, ports that needs window management provided via weston are updated here, https://github.com/krishenriksen/weston-rg351p/releases

**Comment by Txori** [comment]
Hi, I'm experiencing the exact same problem with my RG351M. I had the flowers background. Updating Anberports and redownloading the games didn't change a thing.
I have suppressed AM2R, Spelunky and weston folders, then downloaded the games again, I get the blue screen. Also the weston folder wasn't reinstalled, if that could help you finding the bug.

The flower thing seems to be coming from

**Comment by nullstalgia** [comment]
New AM2R Log.txt: https://gist.github.com/nullstalgia/0a86745f4ece884406903453f2e7bafe

New Spelunky Log.txt: https://gist.github.com/nullstalgia/17d1c1213a6ca9685ee47de2c4c10c3d

**Comment by krishenriksen** [comment]
thanks for logs. It seems the weston is not being updated. Can you check that a red colored "weston-launch" file exist in /home/ark/ ?

**Comment by nullstalgia** [comment]
It exists, but is not red. I ran `sudo chmod +x /home/ark/weston-launch` to see if it would do anything, but no.
The md5 hash of the file is 9487d1273346f1e16cdb5ec263156ddc and is 64928 bytes large.

**Comment by nullstalgia** [comment]
Update, running `weston-launch` complained about not being in the group `weston-launch`

Adding the user `ark` to the group with the command `sudo usermod -aG weston-launch ark` and __Rebooting__ (important), gets some more progress in the launch

**Comment by nullstalgia** [comment]
The games are uncontrollable with dpad and abxy

Moving the left stick shows the mouse, also shows the ArkOS splash screen, covering the game entirely


![image](https://user-images.githubusercontent.com/20761757/109096399-510dca00-76d2-11eb-8dbf-c4bcc5ddddcf.png)

![image](https://user-images.githubusercontent.com/20761757/109096463-6f73c580-76d2-11eb-91e0-93fe56b03244.png)

**Comment by Albinoinverso** [comment]
@nullstalgia woah its a great progress anyway 👏🏽👏🏽

**Comment by krishenriksen** [comment]
The current issues is as follows:

I need to manually rotate Xwayland like we did with SDL2 and SDL1.2
https://wayland.freedesktop.org/xserver.html

And this is similar to the issue regarding input
https://github.com/swaywm/sway/issues/4926

**Comment by Vendo232** [comment]
it has been working for my couple days already ( ArkOS latest.. )

BUT it is unplayable leggy 

![image](https://user-images.githubusercontent.com/44098230/109188842-94a71900-7750-11eb-8eda-cdcd94dae0d5.png)

**Comment by koolKatSauce** [comment]
Rk2020 user here.  Both Spelunky and AM2R display a blue screen and nothing else.  Might be helpful/might not.

**Comment by krishenriksen** [comment]
Currently away, will be back in two weeks.

**Comment by krishenriksen** [comment]
Updated and working, 1.1.5

**Comment by nullstalgia** [comment]
Great work!

However, can I request that the game not close when I hit Select? Seems more suited for Start+Select, instead of taking away a whole button 😄
