### ISSUE TITLE
RG351V 351Elec screen rotated on NAM, Half-Life

### ISSUE THREAD

**Issue by Dahak66** [krishenriksen/AnberPorts#35]
With 351Elec on a 351V  I can start both NAM, and Half-Life but the screens are rotated (and probably in 351p/m resolution. I tried deleting the lib folders in both (similar to the recommended fix for Quake III in  closed issue #8 ) but that just prevented the games from loading altogether and requiring reinstalls from AnberPorts.

**Comment by daedalia** [comment]
For Half-life and maybe NAM, don't delete the entire lib folder, just delete the file with sdl in it's name in the lib folder. Might do it if I remember correctly.

**Comment by Dahak66** [comment]
Thanks! That was exactly it.
