### ISSUE TITLE
Enjoy message shows "nEnjoy"

### ISSUE THREAD

**Issue by nullstalgia** [krishenriksen/AnberPorts#36]
![20210222_152817](https://user-images.githubusercontent.com/20761757/108783636-ad31ec00-7522-11eb-9331-ebd2f9a314b6.jpg)

**Comment by krishenriksen** [comment]
which port ?

**Comment by krishenriksen** [comment]
fixed

**Comment by nullstalgia** [comment]
AM2R and Spelunky, did not test any others.

**Comment by levidunc** [comment]
how do you get avp
