### ISSUE TITLE
Aliens Vs Predator - ARC OS RG351p

### ISSUE THREAD

**Issue by Venegrad** [krishenriksen/AnberPorts#36]
Aliens Vs Predator - ARC OS RG351p
Contols in game is not working

**Comment by Venegrad** [comment]
from steam, avp 2000

**Comment by levidunc** [comment]
edit the controls file

**Comment by levidunc** [comment]
`gamecontrollerdtb.txt`

**Comment by levidunc** [comment]
and can you send me the avp files from steam

**Comment by Venegrad** [comment]
ye sure https://1drv.ms/u/s!AlMuIOVIeFkLk-BlKoU2-bCsmQwuLQ?e=m49NXQ

**Comment by Venegrad** [comment]
```
# quit
back = 311
start = esc
a = enter
b = z
x = c
y = a
l1 = shift
l2 = mouse_left
l3 = mouse_right
r1 = s
r2 = mouse_right
r3 = shift
up = up
down = down
left = left
right = right
left_analog_up = up
left_analog_down = down
left_analog_left = left
left_analog_right = right
right_analog_up = up
right_analog_down = down
right_analog_left = left
right_analog_right = right
```

**Comment by Venegrad** [comment]
> and can you send me the avp files from steam

ye i can, but not in git, cuz i can be banned for that. write your mail

**Comment by levidunc** [comment]
thx

**Comment by levidunc** [comment]
ok
On Sun, May 16, 2021 at 10:18 PM Eugeny ***@***.******@***.***> wrote:
and can you send me the avp files from steam
ye i can, but not in git, cuz i can be banned for that. write your mail
