### ISSUE TITLE
oga_controls crashes/closes when console goes to sleep.

### ISSUE THREAD

**Issue by nullstalgia** [krishenriksen/AnberPorts#38]
![image](https://user-images.githubusercontent.com/20761757/108972924-a8f7f280-7638-11eb-8e80-5ed45b299cf9.png)

So I'm not able to control the game until I close it down and re-open it. (If I even can! I might have to use the Reset button or hold Power)

**Comment by nullstalgia** [comment]
And yep, confirmed that if I run `sudo ./oga_controls &` for the corresponding port, it works just fine again. So some extra daemon of some sort that can just start it again when it crashes could almost be sufficient. :P

**Comment by krishenriksen** [comment]
Thank you, good information. Will fix.

**Comment by krishenriksen** [comment]
I tried with a few ports, and you cannot sleep the device while they are open. EmulationStation will popup over the game when awoken, and other bad things will happen.
