### ISSUE TITLE
quake 3

### ISSUE THREAD

**Issue by szalik-rg351** [krishenriksen/AnberPorts#4]
game loading without problem, you can confirm something, but arrows on d-pad don't work

**Comment by szalik-rg351** [comment]
and there is also arrow in right corner like on drastic

**Comment by krishenriksen** [comment]
You have to use the analog stick in menu.

**Comment by glaucon1984** [comment]
Working fine:
RG351P
ArkOS v1.6 (03/20/2021) Update at least, although I believe I tested it on the current ArkOS version but I'm not 100% sure
AM2R from 1 or 2 weeks ago

Slow framerate:
Same RG351P and MicroSD card
ArkOS v1.6 (04/03/2021) Update
AM2R downloaded 18-20 hours ago

Something different I've also noticed is that when starting the game the initial AM2R screen, with a green planet, is in the bottom-left part of the screen, small, leaving the rest above and on the right in black. This didn't happen previously.
