### ISSUE TITLE
AM2R performance

### ISSUE THREAD

**Issue by glaucon1984** [krishenriksen/AnberPorts#4]
AM2R performance is much worse now, framerate has hiccups in the initial menu, and game feels slower in the beginning of the gameplay, turning unplayable as soon as you move to the right.

RG351P, ArkOS last version.

**Comment by krishenriksen** [comment]
Compared to what ?

**Comment by dhwz** [comment]
Maybe you've used an older AM2R 1.1 build before, this is 1.5.2 now, completely different game (check the version number in the left upper corner).
But I don't have real slowdowns with it, just make sure to disable vsync and the help and scanner display is disabled too, same problems already existed in the old version.

**Comment by glaucon1984** [comment]
Hi, yes, the help causes it to slow down massively, tried vsync settings (it was disabled, actually) and still slow. If the issue is related to the newer version, is it possible to make the older one available? is there a link to 1.1 I can download? sadly I didn't think of making a backup of the previous install.

**Comment by dhwz** [comment]
Just downloaded it again and checked can't see any major slow downs, played hours with that version already. But I'm using 351ELEC.
Maybe @krishenriksen can help or still has the old version too.

**Comment by glaucon1984** [comment]
Just to clarify, the issue I'm reporting is not the "major slowdowns", the issue is the general poorer performance. I cannot measure fps but I'd say it went from solid 60fps to 30-20 depending on how many enemies are currently on screen.

30fps might be considered playable and even smooth, if you have never played the game at 60fps, but for an old-school platformer, it doesn't compensate for the increase in resolution, wide aspect ratio or any bugfixes 1.5.2 might have.

Sadly everything from the repository has been wiped out so I cannot reach any older version of the AM2R.sh script.

**Comment by krishenriksen** [comment]
I've downgraded it to v1.1, should run good again.

**Comment by glaucon1984** [comment]
Yes! this version works much better now. I was thinking, maybe the reason this version is faster is because it runs at less resolution, 1.5.2 supports a wide screen mode that runs internally (I believe) at higher resolution, then it downscales to the RG351P real resolution, giving a better picture quality, but it might impact performance, I wonder if we were to run 1.5.2 at a lower resolution the performance wouldn't improve. I could not find any way to tweak the resoution.

In any case, thank you very much for providing version 1.1, I feel a bit guilty now for those, like @dhwz who might prefer the new one. Maybe it's possible to offer both versions in AnberPorts?

**Comment by krishenriksen** [comment]
> Yes! this version works much better now. I was thinking, maybe the reason this version is faster is because it runs at less resolution, 1.5.2 supports a wide screen mode that runs internally (I believe) at higher resolution, then it downscales to the RG351P real resolution, giving a better picture quality, but it might impact performance, I wonder if we were to run 1.5.2 at a lower resolution the performance wouldn't improve. I could not find any way to tweak the resoution.
> 
> In any case, thank you very much for providing version 1.1, I feel a bit guilty now for those, like @dhwz who might prefer the new one. Maybe it's possible to offer both versions in AnberPorts?

You can just grep the old version 1.5.2 from github, hopefully history will stay now, and I will never add github LFS again, ever. This is what made me have to delete everything. I couldn't download, upload, rename, remove before I purchased LFS bandwidth packs....
