### ISSUE TITLE
QUESTION: When Anberports comes to 351Elec, will there be any omissions?

### ISSUE THREAD

**Issue by thisjustin2001** [krishenriksen/AnberPorts#41]
Hey! As the title says, I'm looking to find out if when Anberports gets ported to 351Elec, if every single game/app is going to get ported, or if there will be any omissions. When I switch from the stock firmware, I plan to switch to 351Elec, and not ArkOS. I know ArkOS runs on Ubuntu and 351Elec doesn't. That's what my concern that maybe not everything will be ported is based on. I'm not sure whether or not some of the games/apps are relying on an Ubuntu based OS to work or not.

ArkOS already has Sonic Robo Blast 2, Spelunky and AM2R, which are games I'm ecstatic about potentially playing for the first time. It wouldn't be the end of the world if I can't play them on 351Elec, but it would really bum me out. Thank you for reading what I have to say! Keep up the great work! I really appreciate all that you're doing for us in the RG351 community!

**Comment by krishenriksen** [comment]
Unknown variables.

**Comment by thisjustin2001** [comment]
Understood! Thanks for the reply!
