### ISSUE TITLE
Jedi Academy - Not booting

### ISSUE THREAD

**Issue by ransisco** [krishenriksen/AnberPorts#43]
I just installed Anberpots but Jedi Academy won't boot. Any suggestion?

And btw, I'm just curious, could this https://github.com/gemrb/gemrb be ported to the 351p version of Anberports at some point?

**Comment by Vendo232** [comment]
same here, JA not starting

**Comment by krishenriksen** [comment]
will look into the issue.

**Comment by krishenriksen** [comment]
fixed.
