### ISSUE TITLE
Frozen on start ip

### ISSUE THREAD

**Issue by TherealGingerone** [krishenriksen/AnberPorts#45]
Hi I have installed Anberports but when I load it from ports I get the main menu but I can’t do anything, none of the controls do anything and I have to hard shutdown to get out of it.
I followed the guide on retro game Corps to install and have tried uninstalling and reinstalling several times.

I’m on the later version of ArkOS

**Comment by pozzy77** [comment]
I'm having same issue

**Comment by TherealGingerone** [comment]
> I'm having same issue

It’s really weird isn’t it

**Comment by krishenriksen** [comment]
Currently away, will be back in two weeks.

**Comment by corvus2219** [comment]
I've got this problem too unfortunately no buttons do anything on the main menu

**Comment by Zigfried15** [comment]
Same here. Using latest Arkos 11.6 (03082021).

**Comment by corvus2219** [comment]
Is this fixed now?

**Comment by TherealGingerone** [comment]
Not for me

**Comment by TherealGingerone** [comment]
Uninstalled again and now working correctly
