### ISSUE TITLE
Aliens Versus Predator - Controls

### ISSUE THREAD

**Issue by russ840** [krishenriksen/AnberPorts#48]
Hi. What are the chances of an AVP classic port. 

Would absolutely love to have this game running on my RG351p

**Comment by danmartzla** [comment]
It's already supported. I've used the "classic" version from Steam and runs well. However, it's unplayable since the controls are not correctly set and there is no way to change them (I didn't find the way). Looks like some kind of key mapping bug or something. I hope it gets solved soon.

**Comment by russ840** [comment]
> It's already supported. I've used the "classic" version from Steam and runs well. However, it's unplayable since the controls are not correctly set and there is no way to change them (I didn't find the way). Looks like some kind of key mapping bug or something. I hope it gets solved soon.

How did you get it running?

**Comment by danmartzla** [comment]
Just like the other games:

1. Update AnberPorts to the latest version
2. Run it and select Alien vs Predator in the game list (which runs [this](https://github.com/krishenriksen/AnberPorts/blob/master/AnberPorts/scripts/games/Alien-vs-Predator))
3.  Copy the files from the Steam version of the game in the "avp" folder in ports
4. Play the game.

The game runs smoothly but it's unplayable to me since analog sticks don't respond.

**Comment by krishenriksen** [comment]
Currently away, will be back in two weeks.

**Comment by russ840** [comment]
> Just like the other games:
> 
> 1. Update AnberPorts to the latest version
> 2. Run it and select Alien vs Predator in the game list (which runs [this](https://github.com/krishenriksen/AnberPorts/blob/master/AnberPorts/scripts/games/Alien-vs-Predator))
> 3. Copy the files from the Steam version of the game in the "avp" folder in ports
> 4. Play the game.
> 
> The game runs smoothly but it's unplayable to me since analog sticks don't respond.

Thanks. That worked. As you said. The controls are useless. Hoping this can be fixed.

**Comment by russ840** [comment]
> Currently away, will be back in two weeks.

Any chance you can fix this ?

**Comment by krishenriksen** [comment]
Fixed, set custom controls in game folder - gamecontrollerdb.txt
