### ISSUE TITLE
Wiki unavailable

### ISSUE THREAD

**Issue by simiadei** [krishenriksen/AnberPorts#5]
The AnberPorts wiki no longer appears to be publicly accessible. The link on the front project page now goes to the sponsorship page, and the link on the sponsorship page (under "Game Files") just goes back to the front project page. Is it gone for good? The data file listings were useful.

**Comment by krishenriksen** [comment]
I had to reset, it will be back soon.

**Comment by nullstalgia** [comment]
Additionally, can you un-hide the releases section on the side bar? It was very convenient. 


![image](https://user-images.githubusercontent.com/20761757/114123166-9f53e280-98a6-11eb-88ab-b999cf25117d.png)

**Comment by krishenriksen** [comment]
Wiki is back!
