### ISSUE TITLE
Moonlight-embedded gamepad defaults are wrong

### ISSUE THREAD

**Issue by Parochus-glitch** [krishenriksen/AnberPorts#5]
Hi, looks like the gamepad defaults are off. Shoulder buttons should be b4 and b5, and triggers should be b10 and b11, left and right in that order. I was able to fix myself, but thought others might have the same problem.

**Comment by krishenriksen** [comment]
You have the gamecontrollerdb.txt ?

**Comment by Parochus-glitch** [comment]
> You have the modified gamecontrollerdb.txt ?

Sure, I’m posting from a mobile device so I’ll attach that when I get to my desktop later.

**Comment by Parochus-glitch** [comment]
Here's the file. Seems to work correctly for me now. 
[gamecontrollerdb.txt](https://github.com/krishenriksen/AnberPorts/files/5863535/gamecontrollerdb.txt)

**Comment by krishenriksen** [comment]
Thank you
