### ISSUE TITLE
Request: Heretic 2

### ISSUE THREAD

**Issue by corvus2219** [krishenriksen/AnberPorts#51]
Honestly have no clue if this can actually happen or not but I thought I might Aswell ask seeing that similar graphic games seem to be going very smooth on the RG351p, my life would be complete if I could play heretic 2 on the go 🙌

**Comment by szalik-rg351** [comment]
https://github.com/hooby3dfx/Heretic2CaS

**Comment by szalik-rg351** [comment]
https://www.doomworld.com/forum/topic/109825-heretic-2-contrast-adaptive-sharpening-openal-eax-and-more/?tab=comments#comment-2037098
