### ISSUE TITLE
Ports not working on 351Elec

### ISSUE THREAD

**Issue by AlanitoTV** [krishenriksen/AnberPorts#53]
I’ve tried updating, downloading, deleting and downloading back games and streaming services like srb2 kart or Nvidia Geforce Now but I couldn’t get it to work. I think the shell script is made for ArkOS but that’s it.

**Comment by Ellun** [comment]
@AlanitoTV I haven't been able to get AnberPorts to show up the console select screen for elec351, but when I dive into the files through the tools, I am able to execute the anberport.sh file to update/download games.

Once a game is downloaded, I dive into the ports directory again to execute the related game file.

Just tested this with the AM2R port.
