### ISSUE TITLE
AM2R does not boot - libGLU.so.1

### ISSUE THREAD

**Issue by sin-amru** [krishenriksen/AnberPorts#55]
Hey !

I'm unable to boot AM2R on RG351P with Arkos and Anberports.
It gets stuck on the Arkos background with the mouse cursor on top that I can move.
Here is the log : 
`Box86 v0.2.1 1ea8dc82 built on Feb 21 2021 01:48:57
Error initializing native libGLU.so.1 (last dlerror is libGLU.so.1: cannot open shared object file: No such file or directory)
Error: loading needed libs in elf /roms/ports/am2r/runner`

Thanks for your awesome work.

**Comment by krishenriksen** [comment]
Just updated and fixed in 1.1.5
