### ISSUE TITLE
AM2R/351ELEC needs patched box86

### ISSUE THREAD

**Issue by bkacjios** [krishenriksen/AnberPorts#59]
On 351elec, the AM2R port does not function. This is mainly because setarch isn't available and the interpreter of the box86 binary is set for a 32bit system, which 351elec is not.

To fix this, I patched the binary with patchelf on another linux system to point to /usr/lib32.

`patchelf --set-interpreter /usr/lib32/ld-linux-armhf.so.3 box86`

Also needed to edit `AM2R.sh` 

```
#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/am2r"

# gl4es
export LIBGL_FB=4

# system
export LD_LIBRARY_PATH=/usr/lib32:$DIR/lib

# box86
export BOX86_ALLOWMISSINGLIBS=1
export BOX86_LD_LIBRARY_PATH=$DIR/lib
export BOX86_LIBGL=$DIR/lib/libGL.so.1
export BOX86_PATH=$DIR/bin

#setarch linux32 -L
$DIR/bin/box86 $DIR/runner 2>&1 | tee -a $DIR/log.txt &
$DIR/bin/oga_controls
```

- Changed LD_LIBRARY_PATH to include /usr/lib32
- Removed setarch

Here's a download for the files I patched if anyone would like to apply them on their own system.
[AM2R.zip](https://github.com/krishenriksen/AnberPorts/files/6178728/AM2R.zip)

**Comment by krishenriksen** [comment]
Fixed
