### ISSUE TITLE
RK2020 - Button Config

### ISSUE THREAD

**Issue by koolKatSauce** [krishenriksen/AnberPorts#60]
What would be the best way to configure the ports to use the RK2020's button layout? 
is it possible to drop a button profile from another app that works in the games folders?  or just edit an existing file?

Thanks!

**Comment by krishenriksen** [comment]
You will have to compile https://github.com/krishenriksen/AnberPorts/tree/master/AnberPorts-Joystick and un-comment `//printf("type:%d code: %d value: %d\n", type, code, value);`

And find the correct values for "int a_key = 304;" etc.
