### ISSUE TITLE
Ports on 351ELEC

### ISSUE THREAD

**Issue by dhwz** [krishenriksen/AnberPorts#62]
Just a question, some (all?) of the ports need adaptions for 351ELEC before they work?
I just tried Quake 2 and 3 (2 complains about root access, 3 has some error with a EGL lib) which don't work currently.

Quake2:
librga:RGA_GET_VERSION:4.00,4.000000 
ctx=0x207d1eb0,ctx->rgaFd=3 
Rga built version:14fb597b 
Quake II shouldn't be run as root! Backing out to save your ass. If
you really know what you're doing, edit src/unix/main.c and remove
this check. But don't complain if Quake II eats your dog afterwards!

Quake3:
./quake3.armv7l: error while loading shared libraries: libEGL.so.1: wrong ELF class: ELFCLASS64

Half-Life / Half-Life Blue-Shift:
librga:RGA_GET_VERSION:4.00,4.000000 
ctx=0x1cca8eb0,ctx->rgaFd=3 
Rga built version:14fb597b

**Comment by pabermod** [comment]
I tested various ports on 351ELEC and all crashes (AvP opens to the main menu but its unresponsive)

**Comment by krishenriksen** [comment]
Fixed
