### ISSUE TITLE
351ELEC (1.1.8) - Roms not working with latest version 

### ISSUE THREAD

**Issue by pabermod** [krishenriksen/AnberPorts#66]
System Shock

> ./systemshock: error while loading shared libraries: libfluidsynth.so.1: cannot open shared object file: No such file or directory

Shadow Warrior

> ./sw: error while loading shared libraries: libjack.so.0: cannot open shared object file: No such file or directory

Half Life Blue Shift

> librga:RGA_GET_VERSION:4.00,4.000000 
ctx=0x2b0c9eb0,ctx->rgaFd=3 
Rga built version:8827628f 

Blood:

> ./nblood: error while loading shared libraries: libogg.so.0: cannot open shared object file: No such file or directory

Exhumed:

> ./pcexhumed: error while loading shared libraries: libogg.so.0: cannot open shared object file: No such file or directory

Jedi Academy:

> /storage/roms/ports/Star Wars Jedi Knight - Jedi Academy.sh: line 8: ./openjk_sp.arm: No such file or directory

Redneck Rampage and Rides Again:

> /storage/roms/ports/Redneck Rampage.sh: line 5: ./rednukem: No such file or directory
/storage/roms/ports/Redneck Rampage Rides Again.sh: line 5: ./rednukem: No such file or directory

**Comment by krishenriksen** [comment]
Fixed
