### ISSUE TITLE
undertale - hide mouse cursor? 

### ISSUE THREAD

**Issue by maartenvd** [krishenriksen/AnberPorts#69]
I couldn't find anything online or in the wiki, but when I start undertale, I always have a mouse cursor in the top right corner. I used the steam assets/runner, is that the issue?

**Comment by krishenriksen** [comment]
there shouldn't be a mouse cursor, unless you use old version, try and update AnberPorts, and reinstall undertale.

**Comment by maartenvd** [comment]
I just did a reinstall. I removed undertale, updated anberports, reinstalled, and still see a mouse cursor in the top right corner. I'm on arkos, if that's relevant?

**Comment by maartenvd** [comment]
aha - updating arkos itself did the trick, probably one of the things I should've tried myself first :)
