### ISSUE TITLE
Blood: Ingame controls not working.

### ISSUE THREAD

**Issue by foriol** [krishenriksen/AnberPorts#7]
Hi, I'm trying to play blood in my Rg351p with ArkOs, but controls aren't working. 
I can navigate through menus with dpad and start/select but when I start a new game I can't move or make any actions.
In other ports like duke nukem or shadow warrior they work fine.
Thanks in advance.

**Comment by krishenriksen** [comment]
Try now.

**Comment by Incubus-dZ** [comment]
Would it be possible to be specific with the files needed to make it work please ? It doesn't start despite many attempts. Thanks

**Comment by krishenriksen** [comment]
There should be a log.txt files in the Blood directory now, if you update and reinstall. This will help you, or you can post it here.
