### ISSUE TITLE
Game Controls + Dialog Menu Controls not working on 351ELEC for RG351V

### ISSUE THREAD

**Issue by nullstalgia** [krishenriksen/AnberPorts#7]
Not sure if this is even supported yet, but I wanted to make the issue so I know when it *is* working. ;)

**Comment by krishenriksen** [comment]
Should be working fine.. let me check.

**Comment by krishenriksen** [comment]
Just tested again, seems to be no issue here with SDL AnberPorts or Dialog AnberPorts.
Also tried Spelunky, works great.

**Comment by nullstalgia** [comment]
Hmm. I ran the update again, and AM2R and Moonlight are still uncontrollable. SDL Menu is fine, however.

**Comment by nullstalgia** [comment]
@krishenriksen Here's a log.txt for AM2R https://gist.github.com/nullstalgia/caff761e9a56acdc50292eb4b1e4f717

**Comment by krishenriksen** [comment]
Trying AM2R, sec.

**Comment by nullstalgia** [comment]
In the meantime, I'll delete Anberports and AM2R and reinstall them and update 351ELEC.

**Comment by krishenriksen** [comment]
Also have fine controls in AM2R here.

**Comment by nullstalgia** [comment]
Still no dice with anything. Any idea on what else I can try? I have SSH access so I can run whatever.

**Comment by krishenriksen** [comment]
ps -a

See if oga_controls is running ?

`/storage/roms/ports/AnberPorts/bin/oga_controls`

**Comment by nullstalgia** [comment]
```
~ # ps -a | grep oga_controls
 2437 root      0:11 /storage/roms/ports/AnberPorts/bin/oga_controls AnberPorts
 3217 root      0:00 grep oga_controls
```

**Comment by krishenriksen** [comment]
`ls /dev/input/`

When running game or AnberPorts

There should be a event3

**Comment by krishenriksen** [comment]
Then do a `evtest` and select event3

**Comment by nullstalgia** [comment]
```
~ # ls /dev/input
by-id    event0   event2   event4   js0
by-path  event1   event3   event5
~ # ^C
~ # evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      rk8xx_pwrkey
/dev/input/event1:      rockchip,rk817-codec Headphones
/dev/input/event2:      rg351-keys
/dev/input/event3:      OpenSimHardware OSH PB Controller
/dev/input/event4:      AnberPorts Joystick
/dev/input/event5:      AnberPorts Joystick
Select the device event number [0-5]: 3
```

Gonna restart it then run again

**Comment by krishenriksen** [comment]
Hmmm it seems oga_controls is running two times ?
or 3, 4 or 5.

**Comment by nullstalgia** [comment]
That could have been due to the way I was killing the stuff without rebooting (htop)

**Comment by nullstalgia** [comment]
```
~ # ls /dev/input
by-id    by-path  event0   event1   event2   event3   js0
~ # ls /dev/input
by-id    by-path  event0   event1   event2   event3   event4   js0
~ # evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      rk8xx_pwrkey
/dev/input/event1:      rockchip,rk817-codec Headphones
/dev/input/event2:      rg351-keys
/dev/input/event3:      OpenSimHardware OSH PB Controller
/dev/input/event4:      AnberPorts Joystick
Select the device event number [0-4]:
```

**Comment by krishenriksen** [comment]
```~/roms/ports/am2r # evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	rk8xx_pwrkey
/dev/input/event1:	rockchip,rk817-codec Headphones
/dev/input/event2:	OpenSimHardware OSH PB Controller
/dev/input/event3:	AnberPorts Joystick
Select the device event number [0-3]:```

Should look like this.

**Comment by nullstalgia** [comment]
So I guess the question is: what's `rg351-keys` ?

**Comment by krishenriksen** [comment]
it's used for moonlight since it can emulate an xbox360 controller. Also used for some other games.

**Comment by nullstalgia** [comment]
https://github.com/351ELEC/351ELEC/commit/7c4b7b8f46a3d688fe34c30741e260fa08a70813#diff-dc5e857b0ed21135a76221ddf6c04c212f60acaa534d24b72436798013fc0e75

Is also mentioned in this commit

**Comment by krishenriksen** [comment]
Let me try and update my 351elec and see whats up.

**Comment by krishenriksen** [comment]
No update is available.

**Comment by nullstalgia** [comment]
Yeah, the one for the 8th is missing the TAR. 

I got it from the 6th, maybe download that one.

![image](https://user-images.githubusercontent.com/20761757/114126824-00cb7f80-98ae-11eb-8991-06835e1e2c5d.png)

**Comment by nullstalgia** [comment]
https://updates.351elec.org/releases/daily/ if you don't know the URL

**Comment by krishenriksen** [comment]
Might be because of rg351v, I test on rg351p

**Comment by nullstalgia** [comment]
Well, I should be able to test anything you need to get it functioning. Considering AM2R scaled perfectly, I have high hopes for the rest once they're controllable.

**Comment by nullstalgia** [comment]
Update 20210408 of 351ELEC did not fix, in case anyone was wondering.

**Comment by krishenriksen** [comment]
Start oga_controls manually with `debug` to see what's up

**Comment by nullstalgia** [comment]
```
~/roms/ports/moonlight-embedded # ./oga_controls -debug
^C
~/roms/ports/moonlight-embedded # ./oga_controls debug
^C
~/roms/ports/moonlight-embedded # ./oga_controls --debug
^C
```

```
~/roms/ports/AM2R # ../AnberPorts/bin/oga_controls debug
^C
~/roms/ports/AM2R # ../AnberPorts/bin/oga_controls -debug
^C
~/roms/ports/AM2R # debug
-sh: debug: command not found
~/roms/ports/AM2R # ../AnberPorts/bin/oga_controls --debug
^C
```

**Comment by daedalia** [comment]
Yeah I'm having the same on the V with Spelunky, Super Crate and They Need to be Fed. Not with Descent or Quake 3. The afore mentioned all use YoYo game runner. I'll post logs in a mo...

**Comment by daedalia** [comment]
**Output from evtest:**
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      rk8xx_pwrkey
/dev/input/event1:      rockchip,rk817-codec Headphones
/dev/input/event2:      rg351-keys
/dev/input/event3:      OpenSimHardware OSH PB Controller
Select the device event number [0-3]:

**Comment by daedalia** [comment]
Spelunky log:
https://drive.google.com/file/d/18ONdSC8qwe7Pce8pSz1xnklzJLHvn2jg/view?usp=sharing

**Comment by nullstalgia** [comment]
In Descent I can navigate the menu, but once in game, I have no control.

**Comment by nullstalgia** [comment]
> 
> 
> **Output from evtest:**
> No device specified, trying to scan all of /dev/input/event*
> Available devices:
> /dev/input/event0: rk8xx_pwrkey
> /dev/input/event1: rockchip,rk817-codec Headphones
> /dev/input/event2: rg351-keys
> /dev/input/event3: OpenSimHardware OSH PB Controller
> Select the device event number [0-3]:

@daedalia is that when Spelunky is open? Or closed

**Comment by daedalia** [comment]
Must've been closed. Tested again with Spelunky open and it's like yours with Anberports Joystick at 4

**Comment by daedalia** [comment]
Controls for Descent no longer work for me in game, neither does Quake 3 since the rotation was fixed in an update.

**Comment by nullstalgia** [comment]
https://github.com/krishenriksen/AnberPorts/blob/master/AnberPorts-Joystick/main.c#L681

This opens event2. For us, that slot is always taken by the wrong device, rg351-keys. Instead, it needs to be searched for.

I will try to set up a build environment so I can test solutions.

**Comment by nullstalgia** [comment]
Just in case, I will ask the 351ELEC devs if this is intentional.

EDIT: Unless this is only something that is ran by AnberPorts.

EDIT: Looking closlier, it looks like that's how they do volume management.

https://github.com/351ELEC/351ELEC/blob/54b22f8e3b5abc554c0b57a3adf5df60b91b51a2/projects/Rockchip/devices/RG351V/packages/linux/patches/02-rg351v.patch#L226

**Comment by krishenriksen** [comment]
>  For us, that slot is always taken by the wrong device, rg351-keys. Instead, it needs to be searched for.
> 
> I will try to set up a build e

ok great, let me fix that.

**Comment by nullstalgia** [comment]
Cheers

I think I see some places I can do some optimization, but I can't get to my normal Linux install, so I hope WSL is good enough.

**Comment by krishenriksen** [comment]
> Cheers
> 
> I think I see some places I can do some optimization, but I can't get to my normal Linux install, so I hope WSL is good enough.

If you have the skills, the mouse movement is stuff very iffy.

**Comment by krishenriksen** [comment]
Should work now. Please test.

**Comment by nullstalgia** [comment]
Bingo!

Also, what build environment are you using? I'm having issues getting the libevdev installed properly. :( Any hints?

**Comment by nullstalgia** [comment]
~~Hmm. Having issues quitting though. It's supposed to be holding Start and Select, right? But nothing happens when I close AM2R/Hold those two.~~

~~Killing `oga_controls` after quitting AM2R normally works.~~

Whoops. That's intentional. Hold Select and then press Start. Got it.

**Comment by daedalia** [comment]
Thank you!
