### ISSUE TITLE
Option for old interface?

### ISSUE THREAD

**Issue by lipnox** [krishenriksen/AnberPorts#73]
I appreciate the effort but new UI runs extremely slow with delay between inputs on the list, looks very clunky and lacks any information. I would massively prefer the old interface how do I switch back?

**Comment by krishenriksen** [comment]
Just a matter of a few more days, and it will shine.

**Comment by lipnox** [comment]
> Just a matter of a few more days, and it will shine.

Awesome, thank you for your hard work.

**Comment by krishenriksen** [comment]
> > Just a matter of a few more days, and it will shine.
> 
> Awesome, thank you for your hard work.

Should work good now.
