### ISSUE TITLE
Heroes of might and magic 3

### ISSUE THREAD

**Issue by l3ll3** [krishenriksen/AnberPorts#9]
Hi,
I'm new to handheld retro gaming and I miss this game from the past. Can you port this?
BR Lelle

**Comment by krishenriksen** [comment]
Only if there is source code somewhere.

**Comment by szalik-rg351** [comment]
https://github.com/vcmi/vcmi this one look up to date
https://github.com/alexxstst/Heroes-of-Might-and-Magic-III this one looks older
